- name: copy mongodb repo
  ansible.builtin.copy:
    src: mongodb.repo
    dest: /etc/yum.repos.d/mongo.repo

- name: Installing mongodb
  ansible.builtin.dnf:
    name: mongodb-org
    state: present

- name: starting mongodb service
  ansible.builtin.service:
    name: mongod
    state: started
    enabled: yes

- name: Replacing mongod.conf file 
  ansible.builtin.replace:
    path: /etc/mongod.conf
    regexp: '127.0.0.1'
    replace: '0.0.0.0'

- name: restarting mongodb service
  ansible.builtin.service:
    name: mongod
    state: restarted