

- name: App-setup
  ansible.builtin.import_role:
    name: common
    tasks_from: app-setup

- name: NodeJS-Setup
  ansible.builtin.import_role:
    name: common
    tasks_from: nodejs

- name: systemd-setup
  ansible.builtin.import_role:
    name: common
    tasks_from: systemd-setup