- name: Upgrade OpenSSL and SSH packages (fix SSL mismatch)
  become: true
  ansible.builtin.dnf:
    name:
      - openssl
      - openssl-libs
      - openssh
      - openssh-server
      - openssh-clients
    state: latest
    update_cache: true
- name: Install Python and build dependencies
  become: true
  ansible.builtin.dnf:
    name:
      - python3
      - python3-devel
      - gcc
    state: installed

- name: Create app directory
  ansible.builtin.file:
    path: /app
    state: directory

- name: Create roboshop user
  ansible.builtin.user:
    name: roboshop
    shell: /sbin/nologin
    system: true
    home: /app

- name: Download payment artifact
  ansible.builtin.get_url:
    url: https://roboshop-artifacts.s3.amazonaws.com/payment-v3.zip
    dest: /tmp/payment.zip

- name: Extract payment artifact
  ansible.builtin.unarchive:
    src: /tmp/payment.zip
    dest: /app
    remote_src: yes

- name: Installing Python requirements
  ansible.builtin.pip:
    requirements: requirements.txt
    executable: pip3.9
  args:
    chdir: /app

- name: copying payment.service file
  ansible.builtin.template:
    src: payment.service.j2
    dest: /etc/systemd/system/payment.service

- name: Shipping systemd-setup
  ansible.builtin.import_role:
    name: common
    tasks_from: systemd-setup
    