- name: disabling nginx
  ansible.builtin.command: dnf module disable nginx -y

- name: enabling nginx:1.24 version
  ansible.builtin.command: dnf module enable nginx:1.24 -y

- name: installing nginx
  ansible.builtin.dnf:
    name: nginx
    state: present

- name: starting nginx service
  ansible.builtin.systemd_service:
    name: nginx
    state: started
    enabled: yes 

- name: removing directory
  ansible.builtin.file:
    path: /usr/share/nginx/html
    state: absent

- name: creating a directory
  ansible.builtin.file:
    path: /usr/share/nginx/html
    state: directory

- name: downloading frontend url
  ansible.builtin.get_url:
    url: https://roboshop-artifacts.s3.amazonaws.com/frontend-v3.zip
    dest: /tmp/frontend.zip

- name: extracting frontend url
  ansible.builtin.unarchive:
    src: /tmp/frontend.zip
    dest: /usr/share/nginx/html
    remote_src: yes

- name: removing default nginx file
  ansible.builtin.file:
   path: /etc/nginx/nginx.conf
   state: absent

- name: copying nginx configuration file
  ansible.builtin.template:
    src: nginx.conf.j2
    dest: /etc/nginx/nginx.conf
  notify:
    - restart nginx

