
- name: installing mysql
  ansible.builtin.dnf: 
    name: mysql-server
    state: present

- name: starting and enabling mysqld service
  ansible.builtin.service:
    name: mysqld
    state: started
    enabled: yes

- name: creating root_user and root_password to mysql
  ansible.builtin.command: mysql_secure_installation --set-root-pass RoboShop@1