- name: disabling nodejs
  ansible.builtin.shell: dnf module disable nodejs -y

- name: enabling nodejs:20 version
  ansible.builtin.shell: dnf module enable nodejs:20 -y

- name: Installing nodejs
  ansible.builtin.dnf:
    name: nodejs
    state: present
    
- name: Installing npm package
  community.general.npm:
    path: /app